server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/seol/IdeaProjects/spring-cloud-ecommerce/git-configuration-yaml
