server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/IdeaProjects/spring-cloud-ecommerce/native-file-repo # [native file system]
        git:
#          uri: file:///Users/seol/IdeaProjects/spring-cloud-ecommerce/git-configuration-yaml # [local git]
          uri: https://github.com/seolys/spring-cloud-ecommerce-config-yaml # [remote git]
#          username: # [remote git] remote repository가 private일때.
#          password: # [remote git] remote repository가 private일때.

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
